### ISSUE TITLE
Could not find file 'napari.yaml' in module 'napari_spotiflow'

### ISSUE THREAD

**Issue by yueqin-sysbio** [weigertlab/napari-spotiflow#7]
**Describe the bug**
Hi! I tried to install napari-spotiflow module on napari. Pip installation returned no error. However, when running napari, I encountered the following error message:
`
ERROR : MainThread : napari.manifest -> 'napari-spotiflow' could not be imported: Could not find file 'napari.yaml' in module 'napari_spotiflow'
`
I've tried to create new conda environment with Python 3.11 and 3.12, and had the same error message.
**To Reproduce**
> conda create -y -n napari-env-3 -c conda-forge napari pyqt python=3.12
> conda activate napari-env-3
> pip install napari-spotiflow
> napari

**Environment (please complete the following information):**
 - Spotiflow version: 0.4.1
 - Conda/mamba version (if applicable):  23.3.1
 - OS: MacOS
 - OS version: 15.5
 - napari version: 0.6.1

**Comment by AlbertDominguez** [comment]
Thanks for reporting, I could replicate! It's probably some packaging issue in the last release, I'll take a look when I have some time during the week! For now, can you try to install version `0.4.0` (`pip install napari-spotiflow==0.4.0`)? Seems to work for me.

**Comment by yueqin-sysbio** [comment]
Thank you! I've tried installing version `0.4.0` and was able to launch spotiflow on napari. I needed to downgrade numpy to versions <2 and I'm currently using `numpy == 1.26.4`. When I tried to detect spots on either my own image or example HybISS image, napari crashes without error message after model running. And this happened for both `hybiss` and `general` pretrained models. The output for example HybISS image before napari crashing is below:
```
INFO:spotiflow.model.spotiflow:Loading pretrained model: hybiss
23:45:50 : INFO : MainThread : Loading pretrained model: hybiss
INFO:spotiflow.model.spotiflow:Will use device: mps:0
23:45:51 : INFO : MainThread : Will use device: mps:0
INFO:spotiflow.model.spotiflow:Predicting with prob_thresh = [0.5319999999999999], min_distance = 2
23:45:51 : INFO : MainThread : Predicting with prob_thresh = [0.5319999999999999], min_distance = 2
INFO:spotiflow.model.spotiflow:Peak detection mode: fast
23:45:51 : INFO : MainThread : Peak detection mode: fast
INFO:spotiflow.model.spotiflow:Image shape (512, 512, 1)
23:45:51 : INFO : MainThread : Image shape (512, 512, 1)
INFO:spotiflow.model.spotiflow:Predicting with (1, 1) tiles
23:45:51 : INFO : MainThread : Predicting with (1, 1) tiles
INFO:spotiflow.model.spotiflow:Padding to shape (512, 512, 1)
23:45:51 : INFO : MainThread : Padding to shape (512, 512, 1)
```

Do you know what might be wrong or how might I obtain more insightful error message for debugging?

**Comment by AlbertDominguez** [comment]
Hmm strange, did you try on a fresh env? And why did you need to downgrade numpy? I just did a fresh install and seems to run with `numpy==2.2.6`.

I think the issue lies with Spotiflow itself now, not the plugin, and is probably related to numpy. To try getting a more useful debug message, can you try the following command to run a prediction with the API:
`python -c "from spotiflow.model import Spotiflow;from spotiflow.sample_data import test_image_hybiss_2d;img=test_image_hybiss_2d();model=Spotiflow.from_pretrained('general'); spots,_=model.predict(img);print('ok')"`. Let me know what that outputs!

**Comment by AlbertDominguez** [comment]
@yueqin-sysbio JFYI, I just released a new version of the plugin which fixes the original issue. Feel free to try running it by creating a new env and installing the latest version as you were doing before 🙂

**Comment by yueqin-sysbio** [comment]
Thank you! I have tried the latest napari-spotiflow and the problem persists. 
I downgraded numpy because when I import example spotiflow image or open spotiflow plugin, I run into the following error message: 

![Image](https://github.com/user-attachments/assets/a5745924-323a-4cec-894f-0fca49d94692)

A similar error message was incurred when running the command line with default `numpy==2.2.6 `

![Image](https://github.com/user-attachments/assets/8f5abd72-2daa-4bd2-82ad-de077ed1aaf0)

When I downgrade to `numpy==1.26.4`, the command line seems to be running fine:

![Image](https://github.com/user-attachments/assets/3a57cf29-b826-4b7a-a9c0-29a4ccb00406)

However, napari quits every time when running the API after downgrading numpy.

**Comment by AlbertDominguez** [comment]
Unfortunately I cannot replicate, seems to work for me also in a MacOS laptop without any need to downgrade numpy. Can you try to install spotiflow through `conda-forge` instead of letting `pip` install it with the plugin? The sequences of commands would be:
```bash
conda create -y -n napari-env-test -c conda-forge napari pyqt spotiflow python=3.12
conda activate napari-env-test
python -c "from spotiflow.model import Spotiflow;from spotiflow.sample_data import test_image_hybiss_2d;img=test_image_hybiss_2d();model=Spotiflow.from_pretrained('general'); spots,_=model.predict(img);print('ok')" # to test the spotiflow installation itself
pip install napari-spotiflow
napari
```

**Comment by yueqin-sysbio** [comment]
Thank you so much! We were able to successfully install and run this now :)
